<!-- Youth Quality of Life-Short Form Instrument (YQOL-SF) -->

<h1>Youth Quality of Life-Short Form Instrument (YQOL-SF)</h1>

<p>YQOL-Short Form (YQOL-SF): A 10 item generic Quality of life instrument. The Youth Quality of Life Instrument - Short Form (YQOL-SF) was developed as a 10-item stand-alone version of the 41-item Youth Quality of Life Instrument - Research Version (YQOL-R).  It differs from the Youth Quality of Life Instrument - Surveillance Version (YQOL-S), in that it represents the domains of the longer YQOL-R.</h3>

<ul>
<li><a href="https://catalysttools.washington.edu/webq/survey/seaqol/92344" target="_blank">Click Here to Order the YQOL-SF</a></li>
<li><a href="http://depts.washington.edu/yqol/docs/YQOL-SF-Order-Form.pdf" target="blank">PDF of Order Form</a></li>
</ul>
